### ISSUE TITLE
Fail on startup

### ISSUE THREAD

**Issue by josericardomcastro** [tkestack/gpu-admission#12]
Hello! 

I'm trying to use gpu-admission with gpu-manager and installing in my cluster on masters node with gpu-admission.yaml.

But the pod is getting error.
```
F1026 16:50:08.270952       1 main.go:83] Failed to new gpu quota filter: invalid GPUFilter config in file /etc/kubernetes/gpu-admission.config
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002f9e00, 0xc000312000, 0x90, 0xe5)
	/go/pkg/mod/k8s.io/klog@v0.3.1/klog.go:855 +0xb8
k8s.io/klog.(*loggingT).output(0x1ebf960, 0xc000000003, 0xc00030a4d0, 0x1e29c93, 0x7, 0x53, 0x0)
	/go/pkg/mod/k8s.io/klog@v0.3.1/klog.go:806 +0x351
k8s.io/klog.(*loggingT).printf(0x1ebf960, 0x3, 0x13ed31a, 0x22, 0xc00016df10, 0x1, 0x1)
	/go/pkg/mod/k8s.io/klog@v0.3.1/klog.go:705 +0x14b
k8s.io/klog.Fatalf(...)
	/go/pkg/mod/k8s.io/klog@v0.3.1/klog.go:1256
main.main()
	/root/rpmbuild/BUILD/gpu-admission-unknown/main.go:83 +0x3ff

```

i am using the default `gpu-admission.config`
```
{
	"QuotaConfigMapName": "gpuquota",
	"QuotaConfigMapNamespace": "kube-system",
	"GPUModelLabel": "gaia.tencent.com/gpu-model",
	"GPUPoolLabel": "gaia.tencent.com/gpu-pool"
}
```

Can anyone help me?

**Comment by mYmNeo** [comment]
Did you use pre-built image or your custom built one?

**Comment by josericardomcastro** [comment]
Yes, i used pre-build image. I created the image with the command: make img

**Comment by mYmNeo** [comment]
Did you put your config file at /etc/kubernetes/gpu-admission.config?

**Comment by josericardomcastro** [comment]
Yes! When i use the pre-build image, the created image has this config file. I checked entering the container image.

**Comment by josericardomcastro** [comment]
Problem solved! I use rancher with rockeros and my the k8s folder is /rke/opt/etc/kubernetes
